// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD875HPJqSjVTNIb9_-ymBsP52cm5w1W28',
    appId: '1:357194150997:android:fb978e15e4d6864ff250dc',
    messagingSenderId: '357194150997',
    projectId: 'relove-73aaf',
    storageBucket: 'relove-73aaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo0By6uHPrbOIToaa-2fl4JUmjcxzjIZw',
    appId: '1:357194150997:ios:d78db6f2f3d6a0ecf250dc',
    messagingSenderId: '357194150997',
    projectId: 'relove-73aaf',
    storageBucket: 'relove-73aaf.appspot.com',
    iosClientId: '357194150997-gd0grfndqfkpf7ln4ngbnuo7jgdj5v7i.apps.googleusercontent.com',
    iosBundleId: 'com.smellycloud.relove',
  );
}
